In [30]:
#Matrix creation and updation

A = zeros(3,4)

B = ones(3,3)

C= rand(3,3)*100

size(C,2)

3

In [21]:
#Reshape (When number if elements in the Matrix is Equal to the Multiplication)

mat1 = reshape(C,1,3,3)

println(size(mat1,2))

mat1 = reshape(1:16,(4,4))

3


4×4 reshape(::UnitRange{Int64}, 4, 4) with eltype Int64:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [44]:
#Indexing used in the matrices

# Remeber the size functions 1 if the dimension doesnt exist 
# Example c[1,4] is not possible but size(c,4) is 1

for i in 1:size(C,1), j in 1:size(C,2) 
    println("C[$i,$j] = ", C[i,j]) #
end

size(C,4) # -> 1
size(C, 2) # -> 3

C[1,1] = 95.48040155714457
C[1,2] = 43.91118186446771
C[1,3] = 1.980990667657767
C[2,1] = 41.68953719097244
C[2,2] = 4.621268984478499
C[2,3] = 12.995006950476418
C[3,1] = 88.7292455577512
C[3,2] = 88.20350181008703
C[3,3] = 55.40551966009373


3

In [65]:
A = rand(3,3) * 100
A = round.(A)


3×3 Matrix{Float64}:
 99.0  91.0  50.0
 33.0  89.0  83.0
 10.0  54.0  51.0

In [67]:
# Transpose 

A'

A .*A'

transpose(A)  # non-conjugate transpose
A'            # conjugate transpose (for complex numbers)


3×3 adjoint(::Matrix{Float64}) with eltype Float64:
 99.0  33.0  10.0
 91.0  89.0  54.0
 50.0  83.0  51.0

In [68]:
A = [1 5; 3 7]
mask = A .> 4          # Matrix of true/false
A[mask]                # Extract elements > 4 → [5, 7]


2-element Vector{Int64}:
 5
 7

In [72]:
using LinearAlgebra
det(A)  # -2.0
inv(A)  # returns the inverse of A
eigvals(A)    # Only eigenvalues
eigvecs(A)    # Only eigenvectors
eigen(A)      # returns both
rank(A)
nullspace(A)  # returns basis of nullspace


2×0 Matrix{Float64}

In [73]:
using Pkg
# Used for the Advanced Math and Computation and Calculus 
Pkg.add("ForwardDiff")


    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
   Installed x265_jll ───────────────────── v3.5.0+0
   Installed libdecor_jll ───────────────── v0.2.2+0
   Installed JpegTurbo_jll ──────────────── v3.1.1+0
   Installed libfdk_aac_jll ─────────────── v2.0.3+0
   Installed Libmount_jll ───────────────── v2.41.0+0
   Installed GR_jll ─────────────────────── v0.73.14+0
   Installed ShowCases ──────────────────── v0.1.0
   Installed JuliaFormatter ─────────────── v2.1.2
   Installed ContextVariablesX ──────────── v0.1.3
   Installed Preferences ────────────────── v1.4.3
   Installed LoggingExtras ──────────────── v1.1.0
   Installed Accessors ──────────────────── v0.1.42
   Installed LERC_jll ───────────────────── v4.0.1+0
   Installed Opus_jll ───────────────────── v1.3.3+0
   Installed Xorg_xkbcomp_jll ───────────── v1.4.7+0
   Installed RelocatableFolders ─────────── v1.0.1
   Installed NNlib ──────────────────────── v0.9.30
   Installed Inli